spin_manifest_version = 2

[application]
name = "sparrow"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "sparrow"

[component.sparrow]
source = "target/wasm32-wasi/release/sparrow.wasm"
sqlite_databases = ["default"]
allowed_outbound_hosts = []
[component.sparrow.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.sparrow.tool.spin-test]
# A relative path to where the built test component binary will live.
source = "target/wasm32-wasi/release/wasm_test.wasm"
# A command for building the target component.
build = "cargo component build --release --target-dir=../target"
# The directory where the `build` command should be run.
dir = "./tests"
