-- Add migration script here
CREATE TABLE user (
    uuid TEXT NOT NULL,
    email TEXT DEFAULT "" NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    encrypted_password TEXT DEFAULT "" NOT NULL,
    reset_password_token TEXT,
    reset_password_sent_at INTEGER,
    sign_in_count INTEGER DEFAULT 0 NOT NULL,
    current_sign_in_at INTEGER,
    last_sign_in_at INTEGER,
    admin BOOLEAN DEFAULT FALSE NOT NULL,
    confirmation_token TEXT,
    confirmed_at INTEGER,
    confirmation_sent_at INTEGER,
    unconfirmed_email TEXT,
    locale TEXT,
    encrypted_otp_secret TEXT,
    encrypted_otp_secret_iv TEXT,
    encrypted_otp_secret_salt TEXT,
    consumed_timestep INTEGER,
    otp_required_for_login BOOLEAN DEFAULT FALSE NOT NULL,
    last_emailed_at INTEGER,
    otp_backup_codes TEXT,
    account_id INTEGER NOT NULL,
    disabled BOOLEAN DEFAULT FALSE NOT NULL,
    moderator BOOLEAN DEFAULT FALSE NOT NULL,
    invite_id INTEGER,
    chosen_languages TEXT,
    created_by_application_id INTEGER,
    approved BOOLEAN DEFAULT true NOT NULL,
    sign_in_token TEXT,
    sign_in_token_sent_at INTEGER,
    webauthn_id TEXT,
    sign_up_ip TEXT,
    skip_sign_in_token BOOLEAN,
    role_id INTEGER,
    settings TEXT,
    time_zone TEXT
);

