 INSERT INTO account(
    username, 
    domain, 
    private_key,
    public_key,
    created_at,
    updated_at,
    note,
    display_name,
    uri,
    url,
    avatar_file_name,
    avatar_content_type,
    avatar_file_size,
    avatar_updated_at,
    header_file_name,
    header_content_type,
    header_file_size,
    header_updated_at,
    avatar_remote_url,
    locked,
    header_remote_url,
    last_webfingered_at,
    inbox_url,
    outbox_url,
    shared_inbox_url,
    followers_url,
    protocol,
    memorial,
    moved_to_account_id,
    featured_collection_url,
    fields,
    actor_type,
    discoverable,
    also_known_as,
    silenced_at,
    suspended_at,
    hide_collections,
    avatar_storage_schema_version,
    header_storage_schema_version,
    devices_url,
    suspension_origin,
    sensitized_at,
    trendable,
    reviewed_at,
    requested_review_at,
    indexable       
 ) VALUES(
    "seungjin",
    "ap.dev.seungjin.net",
    "",
    "",
    
 
 );
            id                         INTEGER PRIMARY KEY AUTOINCREMENT,
            username                      TEXT DEFAULT "" NOT NULL,
            domain                        TEXT,
            private_key                   TEXT,
            public_key                    TEXT DEFAULT "" NOT NULL,
            created_at                    INTEGER NOT NULL,
            updated_at                    INTEGER NOT NULL,
            note                          TEXT DEFAULT "" NOT NULL,
            display_name                  TEXT DEFAULT "" NOT NULL,
            uri                           TEXT DEFAULT "" NOT NULL,
            url                           TEXT,
            avatar_file_name              TEXT,
            avatar_content_type           TEXT,
            avatar_file_size              INTEGER,
            avatar_updated_at             INTEGER,
            header_file_name              TEXT,
            header_content_type           TEXT,
            header_file_size              INTEGER,
            header_updated_at             INTEGER,
            avatar_remote_url             TEXT,
            locked                        BOOLEAN DEFAULT FALSE NOT NULL,
            header_remote_url             TEXT DEFAULT "" NOT NULL,
            last_webfingered_at           INTEGER,
            inbox_url                     TEXT DEFAULT "" NOT NULL,
            outbox_url                    TEXT DEFAULT "" NOT NULL,
            shared_inbox_url              TEXT DEFAULT "" NOT NULL,
            followers_url                 TEXT DEFAULT "" NOT NULL,
            protocol                      INTEGER NOT NULL,
            memorial                      BOOLEAN DEFAULT FALSE NOT NULL,
            moved_to_account_id           INTEGER,
            featured_collection_url       TEXT,
            fields                        VALUE,
            actor_type                    TEXT,
            discoverable                  BOOLEAN,
            also_known_as                 TEXT,
            silenced_at                   INTEGER,
            suspended_at                  INTEGER,
            hide_collections              BOOLEAN,
            avatar_storage_schema_version INTEGER,
            header_storage_schema_version INTEGER,
            devices_url                   TEXT,
            suspension_origin             INTEGER,
            sensitized_at                 INTEGER,
            trendable                     BOOLEAN,
            reviewed_at                   INTEGER,
            requested_review_at           INTEGER,
            indexable                     BOOLEAN
        )"#;